@startuml
top to bottom direction
skinparam packageStyle rectangle

actor Jugador

rectangle "Penguin Legacy F1" {
  usecase "Iniciar sesion local" as UC1
  usecase "Explorar sala" as UC2
  usecase "Interactuar" as UC3
  usecase "Obtener item" as UC4
  usecase "Consultar inventario" as UC5
  usecase "Salir" as UC6
}

Jugador --> UC1
Jugador --> UC2
Jugador --> UC3
Jugador --> UC4
Jugador --> UC5
Jugador --> UC6
UC3 --> UC4
@enduml
